name: Build and Upload Image To Docker Registry

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code (pull code from repo to ubuntu server)
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and push image to docker registry
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vuongninh:latest

      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Deploy to SSH server
        run: echo "Deploy to SSH server"
        # uses: appleboy/ssh-action@master
        # with:
        #   host: ${{ secrets.SSH_HOST }}
        #   username: ${{ secrets.SSH_USERNAME }}
        #   key: ${{ secrets.SSH_PRIVATE_KEY }}
        #   port: ${{ secrets.SSH_PORT }}
        #   script: |
        #     cd ~/application/jcce/jcce-api
        #     sh deploy.sh
